config/routes.rb
Rails.application.routes.draw do
  get 'favorites/create'

  get 'favorites/destroy'

  root 'posts#new'

  devise_for :users
  resources :users, only: [:index, :edit, :update, :show] do
    resource :relationships, only: [:create, :destroy] do
      post :accept, on: :member
    end
    get :favorites, on: :member
    get :follows, on: :member
    get :followers, on: :member
    get :requests, on: :member
  end

  root 'users#index'

  resources :posts do
        resource :favorites, only: [:create, :destroy]
        resource :comments, only: [:create, :destroy]
  end
 
  post '/posts' => 'posts#create'
  get '/posts' => 'posts#index'

  # get '/posts/:id' => 'posts#show', as: 'post'

  # get '/posts/:id/edit' => 'posts#edit', as: 'edit_post'
  patch '/posts/:id' => 'posts#update', as: 'update_post'
  delete '/posts/:id/' => 'posts#destroy', as: 'destroy_post'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
    belongs_to :post

    validates :user, presence: true
    validates :user_id, uniqueness: { scope: :post_id }
    validates :post, presence: true
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user! 
    
  def create
  	@post = Post.find(params[:post_id])
    @favorite = current_user.favorites.build(post: @post)
    # if @favorite.save
    #           redirect_to posts_url, notice: "お気に入りに登録しました"
    # else
    #           redirect_to posts_url, alert: "この投稿はお気に入りに登録できません"
    # end
    @favorite.save
  end

  def destroy
  	@post = Post.find(params[:post_id])
  	@favorite = current_user.favorites.find_by!(post_id: params[:post_id])
    @favorite.destroy
    # redirect_to posts_url, notice: "お気に入りを解除しました"
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_favorite.html.erb
<% if post.favorited_by?(current_user) %>
   <%= link_to "Unlike", post_favorites_path(post.id), method: :delete, remote: true %>
<% else %>
   <%= link_to "Like", post_favorites_path(post.id), method: :post, remote: true %>
<% end %>

app/views/favorites/create.html.erb
<h1>Favorites#create</h1>
<p>Find me in app/views/favorites/create.html.erb</p>

app/views/favorites/create.js.erb
$('#favorite-btn-<%= @post.id %>').html("<%= j(render 'favorites/favorite', post: @post) %>")

app/views/favorites/destroy.html.erb
<h1>Favorites#destroy</h1>
<p>Find me in app/views/favorites/destroy.html.erb</p>

app/views/favorites/destroy.js.erb
$('#favorite-btn-<%= @post.id %>').html("<%= j(render 'favorites/favorite', post: @post) %>")