config/routes.rb
Rails.application.routes.draw do
  get 'favorites/create'

  get 'favorites/destroy'

  root 'posts#new'

  devise_for :users
  resources :users, only: [:index, :edit, :update, :show] do
    resource :relationships, only: [:create, :destroy] do
      post :accept, on: :member
    end
    get :favorites, on: :member
    get :follows, on: :member
    get :followers, on: :member
    get :requests, on: :member
  end

  root 'users#index'

  resources :posts do
        resource :favorites, only: [:create, :destroy]
        resource :comments, only: [:create, :destroy]
  end
 
  post '/posts' => 'posts#create'
  get '/posts' => 'posts#index'

  # get '/posts/:id' => 'posts#show', as: 'post'

  # get '/posts/:id/edit' => 'posts#edit', as: 'edit_post'
  patch '/posts/:id' => 'posts#update', as: 'update_post'
  delete '/posts/:id/' => 'posts#destroy', as: 'destroy_post'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :name, presence: true
  validates :name, length: { in: 2..10 }
  validates :introduction, length: { maximum: 50 }
  has_many :posts
  mount_uploader :image, ImageUploader
  has_many :favorites, dependent: :destroy
  
  has_many :active_relationships, -> { where(accepted: true) }, class_name: 'Relationship', foreign_key: :following_id
  has_many :passive_relationships, -> { where(accepted: true) }, class_name: 'Relationship',foreign_key: :followed_id
  has_many :followings, through: :active_relationships, source: :followed 
  has_many :followers, through: :passive_relationships, source: :following
  
  has_many :comments

  #フォローリクエストが来ているユーザーを集める
  has_many :recieve_requested_relationships, -> { where(accepted: false) }, class_name: "Relationship", foreign_key: :followed_id
  has_many :recieve_requests, through: :recieve_requested_relationships, source: :following

  #自分が送ったフォローリクエストを集める
  has_many :send_requested_relationships, -> { where(accepted: false) }, class_name: "Relationship", foreign_key: :following_id
  has_many :send_requests, through: :send_requested_relationships, source: :followed

  def followed_by?(user)
    # フォローされているユーザーの中から引数に渡されたユーザーがいるかどうかを調べる
    passive_relationships.find_by(following_id: user.id).present?
  end
  
  def recieve_requested_by?(user)
    recieve_requested_relationships.find_by(following_id: user.id).present?
  end

  def send_requested_by?(user)
    send_requested_relationships.find_by(followed_id: user.id).present?
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!
  def new

  end

  def create
  
  end
  
  def index
  	@users = User.all
  end

  def show
  	@user = User.find(params[:id])
  	@post = Post.new
    @posts = @user.posts.page(params[:page]).per(3)

  end
  
  def edit
  	@user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(email: params[:user][:email], locked: params[:user][:locked])
    redirect_to user_path(@user), notice: 'ユーザー情報を更新しました!' 
    else
    render :edit, notice: 'ユーザー情報を更新できませんでした...' 
    end
  end

  def favorites
    @user = User.find(params[:id])
  end

  # フォローしているユーザー一覧を表示するためのアクション
  def follows
   @user = User.find(params[:id])
   @follows = @user.followings
  end

  # フォロワー一覧を表示するためのアクション
  def followers
   @user = User.find(params[:id])
   @followers = @user.followers
  end

  def requests
    @user = User.find(params[:id]) 
    @requests = @user.recieve_requests
  end

  private
  def post_params
    params.require(:user).permit(:name, :introduction, :image)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="container">
	<%= form_for(@user) do |f| %>
		<div class="field">
			<%= f.label :name %>
			<%= f.text_field :name %> 
		</div>
		<div class="field">
			<%= f.label :image %>
			<%= f.file_field :image %> 
		</div>

		<div class="field">
		    <%= f.label :'鍵アカウントにしますか?' %>
		    <%= f.check_box :locked, {}, 'true', 'false' %>
		</div>
  
		<div class="actions">
		    <%= f.submit "Create" %>
		</div>
	<% end %>
</div>

app/views/users/favorites.html.erb
<div class="container">

  <h1>Favorites</h1>

  <table class="table">
      <tr>
        <th></th>
        <th></th>
        <th>Title</th>
        <th>Opinion</th>
        <th></th>
        <th></th>
      </tr>
    
      <% @user.favorites.map { |f| f.post }.each do |post| %>
          <tr>
              <% if post.user.image? %>
    　           <td><%= image_tag post.user.image.url %></td>
              <% else %>
    　           <td>noimage</td>
              <% end %>
            
              <td><%= link_to post.user.name, user_path(post.user) %></td>
              <td class="post-title"><%= post.title %></td>
              <td><%= post.body %></td>
              <td><%= post.favorites.count %></td>
              <td><div id="favorite-btn-<%= post.id %>"><%= render 'favorites/favorite', post: post %></div></td>
          </tr>
      <% end %>
  </table>

</div>

app/views/users/followers.html.erb
<div class="container">
    <h1>Followers</h1>
    <table class="table table-striped">

      <% @followers.each do |user|  %>
        <tr>
          <% if @user.image? %>
        　   <td><%= image_tag @user.image.url %></td>
          <% else %>
        　   <td>noimage</td>
          <% end %>
          <td><%= link_to user.name, user_path(user) %></td>
          <td>
            <div id="follow-btn-<%= user.id %>"><%= render 'relationships/follow', user: user %></div>
          </td>
        </tr> 
      <% end %>
    </table>
</div>

app/views/users/follows.html.erb
<div class="container">

    <h1>Followings</h1>
    <table class="table table-striped">
      
      <% @follows.each do |user| %>
        <tr>
          <% if @user.image? %>
        　   <td><%= image_tag @user.image.url %></td>
          <% else %>
        　   <td>noimage</td>
          <% end %>
          <td><%= link_to user.name, user_path(user) %></td>
          <td>
            <div id="follow-btn-<%= user.id %>"><%= render 'relationships/follow', user: user %></div>
          </td>
        </tr>
      <% end %>
    </table>

</div>

app/views/users/index.html.erb
<div class="container">

    <h2>Users</h2>
    <table class="table table-striped">
      <% @users.each do |user| %>
        <tr>
            <% if user.image? %>
            　<td><%= image_tag user.image.url %></td>
            <% else %>
            　<td>noimage</td>
            <% end %>
            <td><%= link_to user.name,user_path(user) %></td>
            <td>
              <div id="follow-btn-<%= user.id %>"><%= render 'relationships/follow', user: user %></div>
            </td>
        </tr>
      <% end %>
    </table>

</div>

app/views/users/requests.html.erb
<div class="container">

    <h1>Requests</h1>

    <table class="table">

        <% @requests.each do |user| %>
          <tr>
              <% if @user.image? %>
                　<td><%= image_tag @user.image.url %></td>
              <% else %>
                　<td>noimage</td>
              <% end %>
              <td><%= link_to user.name, user_path(user) %></td>
              <td><%= link_to 'Permit', accept_user_relationships_path(user.id), method: :post %></td>
              <td><%= link_to 'Refuse', user_relationships_path(user.id), method: :delete %></td>
          </tr>
        <% end %>

    </table>

</div>

app/views/users/show.html.erb
<div class="container">
    <p>Name</p>
    <p><%= @user.name %></p>
    <p>Introduction</p>
    <p><%= @user.introduction %></p>  

    <% if accepted_user?(@user) %>

        <% if @user.image? %>
        　   <p><%= image_tag @user.image.url %></p>
        <% else %>
        　   <p>noimage</p>
        <% end %>

        <% if current_user != @user %> 
        <% else %>
            <button type="button" class="btn btn-default"><%= link_to 'Edit', edit_user_registration_path %></button>
        <% end%>
        <div id="follow-btn-"><%= render 'relationships/follow', user: @user %></div>

        <ul>
            <li>
                <span class="text">Books</span>
                <span class="num"><%= @user.posts.count %></span> 
            </li>
            <li>
                <%= link_to favorites_user_path(@user) do %>
                <span class="text">Favorites</span>
                <span class="num"><%= @user.favorites.count %></span>
                <% end %>     
            </li>
            <li><%= link_to follows_user_path(@user) do %>
                <span class="text">Followings</span>
                <span class="num"><%= @user.followings.count %></span>
                <% end %>
            </li>
            <li><%= link_to followers_user_path(@user) do %>
                <span class="text">Followers</span>
                <span class="num"><%= @user.followers.count %></span>
                <% end %>
            </li>
        </ul>

        <% if @user.locked && @user == current_user %>
            <%= link_to "You have #{@user.recieve_requested_relationships.count} friend requests", requests_user_path(@user) , class: "btn btn-default col-xs-12"%>
        <% end %>

        <h1>newbook</h1>

        <%= render 'posts/form', post: @post %>

        <h1>Books</h1>

        <table class="table">
            <th></th>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th></th>
            <th></th>
            <th>Comment</th>

            <% @posts.each do |post| %>
                <tr>
                    <% if post.user.image? %>
        　               <td><%= image_tag post.user.image.url %></td>
                    <% else %>
        　               <td>noimage</td>
                    <% end %>
                    <td>
                        <div class="user">
                            <span class="user-name"><%= link_to post.user.name, user_path(post.user) %></span>
                        </div>
                    </td>
                    <td>
                        <div class="post-title"><%= link_to post.title, post_path(post) %></div>
                    </td>
                    <td>
                        <div class="post-body"><%= post.body %></div>
                    </td>
                    <td><%= post.favorites.count %></td>
                    <td><div id="favorite-btn-<%= post.id %>"><%= render 'favorites/favorite', post: post %></div></td>
                    <td><%= post.comments.count %></td>
                </tr>
            <% end %>
        </table>

        <%= paginate @posts %>
  
    <% else %>
        <p>This Account is private</p>
    <% end %>

</div>