config/routes.rb
Rails.application.routes.draw do
  get 'favorites/create'

  get 'favorites/destroy'

  root 'posts#new'

  devise_for :users
  resources :users, only: [:index, :edit, :update, :show] do
    resource :relationships, only: [:create, :destroy] do
      post :accept, on: :member
    end
    get :favorites, on: :member
    get :follows, on: :member
    get :followers, on: :member
    get :requests, on: :member
  end

  root 'users#index'

  resources :posts do
        resource :favorites, only: [:create, :destroy]
        resource :comments, only: [:create, :destroy]
  end
 
  post '/posts' => 'posts#create'
  get '/posts' => 'posts#index'

  # get '/posts/:id' => 'posts#show', as: 'post'

  # get '/posts/:id/edit' => 'posts#edit', as: 'edit_post'
  patch '/posts/:id' => 'posts#update', as: 'update_post'
  delete '/posts/:id/' => 'posts#destroy', as: 'destroy_post'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
	validates :title, presence: true
	validates :title, length: { maximum: 200 }
	validates :body, presence: true
	validates :body, length: { maximum: 200 }
	belongs_to :user
	mount_uploader :image, ImageUploader
	has_many :favorites, dependent: :destroy

	def favorited_by? user
        favorites.where(user_id: user.id).exists?
    end
    has_many :comments
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
   before_action :authenticate_user!
   before_action :correct_user, only: [:edit, :update]
   before_action :set_request_from, only: :create

  def new
  	@post = Post.new
  end

  def create
  	@post = Post.new
  	@post.title = params[:post][:title]
  	@post.body = params[:post][:body]
    @post.user_id = current_user.id
    # =User.find(:id)
  	if @post.save
  		redirect_to post_path(@post.id)
  	else
      return_back and return	
    end
  end

  def index
    @posts = Post.page(params[:page]).per(3).includes(:user)
  end

  def show
  	@post = Post.find(params[:id])
    @comments = @post.comments
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.title = params[:post][:title]
    @post.body = params[:post][:body]
    @post.save
    redirect_to post_path(@post.id)
  end

  def destroy
  	@post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  private
  def post_params
    #:user_idを追加
    params.require(:post).permit(:title, :body, :user_id)
  end

  def correct_user
    post = Post.find(params[:id])
    if current_user.id != post.user.id
      redirect_to root_path
    end
  end

  def set_request_from
    if session[:request_from]
      @request_from = session[:request_from]
    end
    # 現在のURLを保存しておく
    session[:request_from] = request.original_url
  end

  def return_back
    if request.referer
      redirect_back(fallback_location: root_path)
    elsif @request_from
      redirect_to @request_from and return true
    end
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(post) do |f| %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>
  
  <div class="actions">
    <%= f.submit "Create Book" %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div class="container">
	<h1>Editing book</h1>
	<%= render 'form', post: @post %>
    <%= link_to "Show", destroy_post_path(@post.id) %>
	<%= link_to 'Back', posts_path %>
</div>

app/views/posts/index.html.erb
<div class="container">
	<h1>Books</h1>
	<table class="table">
	<tr>
	<th></th>
	<th></th>
	<th>Title</th>
	<th>Opinion</th>
	<th></th>
	<th></th>
	<th>Comment</th>
	</tr>
	
	<% @posts.each do |post| %>
	<tr>
		<% if post.user.image? %>
    　	<td><%= image_tag post.user.image.url %></td>
  		<% else %>
    　	<td>noimage</td>
  		<% end %>
			<td><%= link_to post.user.name, user_path(post.user) %></td>
			<td><%= link_to post.title, post_path(post) %></td>
			<td><%= post.body %></td>
			<td><%= post.favorites.count %></td>
			  
			<td><div id="favorite-btn-<%= post.id %>"><%= render 'favorites/favorite', post: post %></div></td>
			<td><%= post.comments.count %></td> 
		<% end %>
	</tr>
	</table>
	<%= paginate @posts %>
</div>

app/views/posts/new.html.erb
<div class="container">
	<p>Name</p>
	<p><%= current_user.name %></p>
	<p>Introduction</p>
	<p><%= current_user.introduction %></p> 
    <% if current_user.image? %>
    	<p><%= image_tag current_user.image.url %></p>
    <% else %>
    　	<p>noimage</p>
    <% end %>
</div>
    
  

  

app/views/posts/show.html.erb
<div class="container">
	<h2>Title</h2>
	<p><%= @post.title %></p>
	<h2>Body</h2>
	<p><%= @post.body %></p>
	<% if current_user.id == @post.user_id %>
	      <%= link_to 'Edit', edit_post_path(@post) %> |
	      <%= link_to 'Destroy', @post, method: :delete, data: { confirm: 'Are you sure?' } %> |
	<% end %>
	<%= form_for([@post,Comment.new]) do |f| %>
  <div>
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit%>
  </div>
  <% end %>
  <% @comments.each do |comment| %>
    <%= comment.user.name %>
    <%= comment.body %>
    <%= link_to 'Destroy', post_comments_path(comment.post), method: :delete, data: { confirm: 'Are you sure?' } %>
  <% end %>
</div>