config/routes.rb
Rails.application.routes.draw do
  get 'favorites/create'

  get 'favorites/destroy'

  root 'posts#new'

  devise_for :users
  resources :users, only: [:index, :edit, :update, :show] do
    resource :relationships, only: [:create, :destroy] do
      post :accept, on: :member
    end
    get :favorites, on: :member
    get :follows, on: :member
    get :followers, on: :member
    get :requests, on: :member
  end

  root 'users#index'

  resources :posts do
        resource :favorites, only: [:create, :destroy]
        resource :comments, only: [:create, :destroy]
  end
 
  post '/posts' => 'posts#create'
  get '/posts' => 'posts#index'

  # get '/posts/:id' => 'posts#show', as: 'post'

  # get '/posts/:id/edit' => 'posts#edit', as: 'edit_post'
  patch '/posts/:id' => 'posts#update', as: 'update_post'
  delete '/posts/:id/' => 'posts#destroy', as: 'destroy_post'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Level1</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  
  	<!-- user_signed_in? はユーザがログインしているか調べるdeviseのHelperメソッド -->
          
          <% if user_signed_in? %> 
            <!-- current_user は現在ログインしているUserオブジェクトを返すdeviseのHelperメソッド -->
            <!-- *_path はUserモデルを作成したときに、
              deviseにより自動で作成されてますので、rake routesで確認できます -->
            
            <div class="bg-info text-right">
              <div class="container">
                <%= link_to 'Home', user_path(current_user) %> ｜
                <%= link_to 'Users', users_path %> ｜
                <%= link_to "Books", posts_path %> ｜
                <%= link_to "Log Out", destroy_user_session_path, method: :delete %>
              </div>
            </div>
            
          <% else %>
            <div class="bg-info text-right">
              <div class="container">
                <%= link_to 'Home', root_path %>｜
                <%= link_to "Sign Up", new_user_registration_path %> |
                <%= link_to "Log Out", new_user_session_path %>
              </div>
            </div>
            
          <% end %>
    <%= yield %>
  </body>
</html>